### ISSUE TITLE
I see a design fail here

### ISSUE THREAD

**Issue by frank-dspeed** [Polyxo/node-cctalk#2]
I tested to implament multi devices multi crc on same bus and regonized that this can't work

a Device needs to implament its commands and expected answers as also it needs to send its commands with the right crc checksums

**Comment by geloescht** [comment]
Thanks for your bug report.
Could you please describe what you expected to work and what didn't work?
Checksums are not implemented yet, if that is what you mean. Please feel free to make a pull request.

**Comment by frank-dspeed** [comment]
@geloescht its all ok you solved that via your commandChain Promise. that you execute only one command and so on don't saw it right and it got messed up because i don't understood what you did.

i have done a complet Refactor of this. 
we can close this.

**Comment by geloescht** [comment]
Awesome. I am really interested in expanding this library to support more devices, so if you have any code that you might be able to contribute, please don't hesitate to do so.

**Comment by frank-dspeed** [comment]
@geloescht  some updates for you we will implament your parser directly into the serialport 5.x+ branches under parsers.cctalk
https://github.com/direktspeed/serialport-parsers-cctalk
https://github.com/EmergingTechnologyAdvisors/node-serialport/issues/1240

I have only a lot of work i also added complet crc16 support and checksum validation if you create a command from a buffer all this stuff but i need to say that the new version is es7 + so i am not sure if you like that for your lib as you use much functions and prototypes.

i am using normal es6 classes and i am planning to add decorator support for events and commands.

so you can do 

```
@escrow
@corePlus
@BillValidator
class myBillValidator extends CCDevice {}
```
